FROM demiddleday3_jupyter:latest

MAINTAINER yoon, koock <deep-learning@kakao.com>

COPY ./ /root/DE-middle/flink/consumer/

WORKDIR /root/DE-middle/flink/consumer/

EXPOSE 8889

CMD /flink/bulid-target/bin/start-cluster.sh

ENTRYPOINT jupyter notebook --allow-root --ip=0.0.0.0 --port=8889 --no-browser